export const USER_ACTIONS = {
    USER_SIGNIN : "USER_SIGNIN",
    USER_LOADING: "USER_LOADING",
    USER_LOADING_DONE : "USER_LOADING_DONE",
    USER_ERROR_LOAD : "USER_ERROR_LOAD",
    USER_ERROR_ERASE : "USER_ERROR_ERASE"
}

export const PRODUCTS_ACTION = {
    PRODUCTS_LOADING : "PRODUCTS_LOADING",
    PRODUCTS_LOADING_DONE : "PRODUCTS_LOADING_DONE",
    GET_PRODUCTS : "GET_PRODUCTS",
    EDIT_PRODUCT : "EDIT_PRODUCT",
}

export const CATEGORY_ACTION = {
    CATEGORY_LOADING : "CATEGORY_LOADING",
    CATEGORY_LOADING_DONE : "CATEGORY_LOADING_DONE",
    GET_CATEGORY : "GET_CATEGORY",
    
}