export const OVERLAY_ACTIONS  ={
    SHOW_OVERLAY :"SHOW_OVERLAY",
    HIDE_OVERLAY :"HIDE_OVERLAY"
}

export const LEFT_BAR = {
    SWITCH_TAB : "SWITCH_TAB",
}

export const USER_ACTIONS = {
    USER_SIGNIN : "USER_SIGNIN",
    USER_LOADING: "USER_LOADING",
    USER_LOADING_DONE : "USER_LOADING_DONE",
    USER_ERROR_LOAD : "USER_ERROR_LOAD",
    USER_ERROR_ERASE : "USER_ERROR_ERASE"
}

export const PRODUCTS_ACTION = {
    PRODUCTS_LOADING : "PRODUCTS_LOADING",
    PRODUCTS_LOADING_DONE : "PRODUCTS_LOADING_DONE",
    GET_PRODUCTS : "GET_PRODUCTS",
    EDIT_PRODUCT : "EDIT_PRODUCT",
    CREATE_PRODUCT :"CREATE_PRODUCT",
    DELETE_PRODUCT : "DELETE_PRODUCT",
    DELETE_PRODUCTS_UNDER_CATEGORY : "DELETE_PRODUCTS_UNDER_CATEGORY"
}

export const CATEGORY_ACTION = {
    CATEGORY_LOADING : "CATEGORY_LOADING",
    CATEGORY_LOADING_DONE : "CATEGORY_LOADING_DONE",
    GET_CATEGORY : "GET_CATEGORY",
    CREATE_CATEGORY : "CREATE_CATEGORY",
    EDIT_CATEGORY : "EDIT_CATEGORY",
    DELETE_CATEGORY : "DELETE_CATEGORY",
    INCREMENT_PROD : "INCREMENT_PROD",
    DECREMENT_PROD : "DECREMENT_PROD"
}

export const CAMPAIGN_ACTION = {
    CAMPAIGN_LOADING : "CAMPAIGN_LOADING",
    CAMPAIGN_LOADING_DONE : "CAMPAIGN_LOADING_DONE",
    CREATE_CAMPAIGN : "CREATE_CAMPAIGN",
    GET_CAMPAIGN : "GET_CAMPAIGN",
    EDIT_CAMPAIGN : "EDIT_CAMPAIGN",
    DELETE_CAMPAIGN : "DELETE_CAMPAIGN"
}

export const SALE_ACTION = {
    SALE_LOADING : "SALE_LOADING",
    SALE_LOADING_DONE : "SALE_LOADING_DONE",
    CREATE_SALE : "CREATE_SALE",
    GET_SALE : "GET_SALE",
    EDIT_SALE : "EDIT_SALE",
    DELETE_SALE : "DELETE_SALE"
}

export const COUPON_ACTION = {
    COUPON_LOADING : "COUPON_LOADING",
    COUPON_LOADING_DONE : "COUPON_LOADING_DONE",
    CREATE_COUPON : "CREATE_COUPON",
    GET_COUPON : "GET_COUPON",
    EDIT_COUPON : "EDIT_COUPON",
    DELETE_COUPON : "DELETE_COUPON"
}

export const CONFIRMATION_ACTION={
    CONFIRMATION_STATUS : "CONFIRMATION_STATUS",
    CONFIRMATION_RESET : "CONFIRMATION_RESET",
}